//
//  SKYWordProtocols.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import Foundation

// MARK: View -

protocol SKYWordViewInput: class {
    func configure(word: APIResponse.SKYWord)
}

protocol SKYWordViewOutput: class {
    func viewDidLoad()
}


// MARK: Presenter -

protocol SKYWordModuleInput: class {
    func configure(word: APIResponse.SKYWord)
}


// MARK: Interactor -

protocol SKYWordInteractorInput: class {
    
}

protocol SKYWordInteractorOutput: class {
    
}


// MARK: Router -

protocol SKYWordRouterInput: class {

}
