//
//  SKYWordAssembly.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import UIKit

class SKYWordAssembly: NSObject {
        
    class func createModule(viewController: SKYWordViewController) {
        let presenter = SKYWordPresenter()
        let interactor = SKYWordInteractor()
        let router = SKYWordRouter()
        let dataManager = SKYWordDataManager()
        
        viewController.output = presenter
        viewController.dataManager = dataManager
        presenter.view = viewController
        presenter.interactor = interactor
        presenter.router = router
        interactor.output = presenter
        router.viewController = viewController
    }
}
