//
//  SKYWordViewController.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import UIKit

class SKYWordViewController: UITableViewController, SKYWordViewInput {

    // MARK: - Public vars & lets
    
	var output: SKYWordViewOutput?
    var dataManager: SKYWordDataManager?
    
    
    // MARK: - Private vars & lets
    
    
    // MARK: - Init

	required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder);
        SKYWordAssembly.createModule(viewController: self)
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        setupInitialState()
        output?.viewDidLoad()
    }
    
    private func setupInitialState() {
        setupTableView()
    }
    
    private func setupTableView() {
        tableView.register(UINib(nibName: SKYMeaningCell.cellNibName(), bundle: nil),
                           forCellReuseIdentifier: SKYMeaningCell.cellIdentifier())
        
        tableView.tableFooterView = UIView()
        tableView.delegate = dataManager
        tableView.dataSource = dataManager
    }
    
    
    // MARK: - SKYWordViewInput
    
    func configure(word: APIResponse.SKYWord) {
        DispatchQueue.main.async {
            self.title = word.text
            self.dataManager?.word = word
            self.tableView.reloadData()
        }
    }

}
