//
//  SKYWordInteractor.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import Foundation
import Alamofire

class SKYWordInteractor: NSObject, SKYWordInteractorInput {
    
    // MARK: - Public vars & lets

    weak var output: SKYWordInteractorOutput?
    
    
    // MARK: - Private vars & lets
    
    internal let apiManager = APIManager(sessionManager: Session())
}
