//
//  SKYSearchRouter.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import UIKit

class SKYSearchRouter: NSObject,  SKYSearchRouterInput {
    
    // MARK: - Public vars & lets
    
    weak var viewController: UIViewController?
    
    
    // MARK: - Private vars & lets
    
    func showWord(word: APIResponse.SKYWord) {
        let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let controller = mainStoryboard.instantiateViewController(withIdentifier: "SKYWordViewController") as! SKYWordViewController
        let presenter = controller.output as! SKYWordPresenter
        presenter.configure(word: word)
        DispatchQueue.main.async {
            self.viewController?.navigationController?.pushViewController(controller, animated: true)
        }
    }

}
