//
//  SKYSearchInteractor.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import Foundation
import Alamofire

class SKYSearchInteractor: NSObject, SKYSearchInteractorInput {
    
    // MARK: - Public vars & lets

    weak var output: SKYSearchInteractorOutput?
    
    
    // MARK: - Private vars & lets
    
    internal let apiManager = APIManager(sessionManager: Session())
    private let operationQ = OperationQueue()
    
    
    // MARK: - SKYSearchInteractorInput
    
    func doRequest(text: String) {
        operationQ.cancelAllOperations()
        operationQ.addOperation {
            self.apiManager.makeRequest(type: RequestItemsType.search, params: ["search": text]) {
                (res: Swift.Result<[APIResponse.SKYWord], AlertMessage>) in
                switch res {
                case .success(let words):
                    self.output?.response(data: words)
                    break
                case .failure(let message):
                    self.output?.error(error: message.localizedDescription)
                    break
                }
            }
        }
    }
    
}
