//
//  SKYSearchProtocols.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import Foundation

// MARK: View -

protocol SKYSearchViewInput: class {
    func configure(data: [APIResponse.SKYWord])
}

protocol SKYSearchViewOutput: class {
    func viewDidLoad()
    func textDidChange(text: String)
    func wordDidSelected(word: APIResponse.SKYWord)
}


// MARK: Presenter -

protocol SKYSearchModuleInput: class {

}


// MARK: Interactor -

protocol SKYSearchInteractorInput: class {
    func doRequest(text: String)
}

protocol SKYSearchInteractorOutput: class {
    func response(data: [APIResponse.SKYWord])
    func error(error: String)
}


// MARK: Router -

protocol SKYSearchRouterInput: class {
    func showWord(word: APIResponse.SKYWord)
}
