//
//  SKYSearchRouter.swift
//  Skyeng
//
//  Created Kirill Shalankin on 15.09.2020.
//  Copyright © 2020 Kirill Shalankin. All rights reserved.
//
//  Template generated by Kirill Shalankin
//

import UIKit

class SKYSearchRouter: NSObject,  SKYSearchRouterInput {
    
    // MARK: - Public vars & lets
    
    weak var viewController: UIViewController?
    
    
    // MARK: - Private vars & lets

}
